# Generated by Django 3.0.8 on 2020-07-15 16:47

from django.db import migrations

def create_data(apps, schema_editor):
    Login = apps.get_model('login', 'Login')
    Login(username = "jtrombley", password = "password", first_name="Josh", last_name="Trombley", email="josh.trombley@icloud.com").save()

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
    ]
